---
- name: Install common utilities
  package:
    name:
      - nmap
      - ranger
      - htop
      - btop
      - plocate
      - xsel
      - wget
      - curl
      - tmux
      - ffmpeg
      - imagemagick
      - nano
      - tldr
      - traceroute

    state: present
