---
- name: Install Python Utils
  ansible.builtin.pip:
    name:
      - git-remote-dropbox
      - ansible-lint
      - hy
      - ipython
      - jedhy
      - mccabe
      - pycodestyle
      - pyflakes
      - python-lsp-server
      - vosk
    state: present
