---
- name: Install 
  become: true
  ansible.builtin.package:
    name: "{{ wayland-arch }}"
    state: present

- name: Install packages for wayland
  become: true
  become_user: aur_builder
  become_method: sudo
  kewlfft.aur.aur:
    name: "{{ wayland-aur }}"
    use: yay
    state: present
