[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[general]
import = [
    "/home/ewhd/.config/omarchy/current/theme/alacritty.toml",
    "/home/ewhd/.config/alacritty/themes/themes/gruvbox_dark.toml",
]

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "Copy"
key = "Insert"
mods = "Control"

[window]
decorations = "None"

[window.padding]
x = 14
y = 14
